apiVersion: v1
metadata:
  name: asm-options
  namespace: istio-system
data:
  multicluster_mode: connected
  mesh: |-
    accessLogFile: /dev/stdout
    trustDomainAliases: ["{{PROJECT_ID}}.svc.id.goog"]
kind: ConfigMap
